spring:
  profiles:
    active: dev
  cloud:
    loadbalancer:
      ribbon:
        enabled: false


service:
  feign:
    k8s-provider:
      name: xincan-k8s-provider
      url: 172.16.124.140:30300/api
